"""criar tabela paciente

Revision ID: 40cd47387689
Revises: 
Create Date: 2026-02-02 19:53:47.532369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40cd47387689'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('dataNasc', sa.String(), nullable=False),
    sa.Column('setorClinico', sa.String(), nullable=False),
    sa.Column('leito', sa.Integer(), nullable=False),
    sa.Column('datain', sa.Integer(), nullable=False),
    sa.Column('risco', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Paciente_id'), 'Paciente', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Paciente_id'), table_name='Paciente')
    op.drop_table('Paciente')
    # ### end Alembic commands ###
