"""colunas_auditoria

Revision ID: 7563a0b5763f
Revises: 40cd47387689
Create Date: 2026-02-07 19:29:08.381688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7563a0b5763f'
down_revision: Union[str, Sequence[str], None] = '40cd47387689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Paciente', sa.Column('criado_em', sa.DateTime(), nullable=True))
    op.add_column('Paciente', sa.Column('atualizado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Paciente', 'atualizado_em')
    op.drop_column('Paciente', 'criado_em')
    # ### end Alembic commands ###
